apiVersion: v1
kind: Secret
metadata:
  name: foodtrack-api-config
type: Opaque
stringData:
  INGEST_TOKEN: "__VALEUR_INJECTEE_AU_DEPLOIEMENT__"
  CACHE_PASSWORD: "__VALEUR_INJECTEE_AU_DEPLOIEMENT__"
