# Assemble les ressources communes installees une seule fois dans le cluster.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# La StorageClass sera ensuite referencee par le StatefulSet Redis.
resources:
  - storageclass.yaml
