apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: foodtrack-dev
resources:
  - namespace.yaml
  - ../../base
configMapGenerator:
  - name: foodtrack-config
    behavior: merge
    files:
      - index.html
    literals:
      - ENVIRONMENT=dev
      - SEUIL_TEMPERATURE_C=8
      - NIVEAU_JOURNAL=debug
replicas:
  - name: portail-qualite
    count: 1
patches:
  - target:
      kind: StatefulSet
      name: cache-releves
    patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 10Gi

  - path: hpa-patch.yaml
